#!/bin/sh
# Regenerate rtl/index.qip: every RTL file the core needs, in a stable order.
# Run from the repo root whenever a file is added or removed.
set -e
out=rtl/index.qip
{
echo "# =============================================================================="
echo "# S.T.U.N. Runner core RTL -- generated by tools/gen_qip.sh, do not edit"
echo "# =============================================================================="
echo 'set_global_assignment -name SEARCH_PATH [file join $::quartus(qip_path) ""]'
for f in $(cd rtl && ls *.sv gsp/*.sv adsp/*.sv jsa/*.sv 2>/dev/null | sort); do
    echo "set_global_assignment -name SYSTEMVERILOG_FILE [file join \$::quartus(qip_path) \"$f\"]"
done
echo ""
echo "# TG68K.C 68000/68010/68020 kernel (LGPL, Tobias Gubener), GHDL-converted"
echo 'set_global_assignment -name VERILOG_FILE [file join $::quartus(qip_path) "../modules/cpu-tg68k/gen/tg68k.v"]'
echo "# T65 6502 (BSD, Daniel Wallner / MikeJ), GHDL-converted"
echo 'set_global_assignment -name VERILOG_FILE [file join $::quartus(qip_path) "../modules/cpu-t65/gen/t65.v"]'
echo "# jt51 YM2151 and jt6295 OKI MSM6295 (GPL-3, Jose Tejada)"
for f in $(cd modules/sound-jt51/hdl && ls *.v | sort); do
    echo "set_global_assignment -name VERILOG_FILE [file join \$::quartus(qip_path) \"../modules/sound-jt51/hdl/$f\"]"
done
for f in $(cd modules/sound-jt6295/hdl && ls *.v | sort); do
    echo "set_global_assignment -name VERILOG_FILE [file join \$::quartus(qip_path) \"../modules/sound-jt6295/hdl/$f\"]"
done
echo 'set_global_assignment -name SEARCH_PATH [file join $::quartus(qip_path) "../modules/sound-jt6295/hdl"]'
} > $out
echo "wrote $out ($(grep -c FILE $out) files)"
